version: '3.3'
networks:
  redis:
    external:
      name: redis
services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    restart: always
    networks:
      - redis
    ports:
      - '6379:6379'
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_PORT=6379'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
  redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    restart: always
    networks:
      - redis
    ports:
      - '6379:6379'
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_PORT=6379'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
  redis-cluster-init:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    restart: always
    networks:
      - redis
    ports:
      - '6379:6379'
    depends_on:
      - redis-node-0
      - redis-node-1
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDISCLI_AUTH=bitnami'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - 'REDIS_CLUSTER_CREATOR=yes'
volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local