version: '3.5'

networks:
  prefect:
    name: prefect


services:
  # --------------------------------------#
  #             Prefect server              #
  # --------------------------------------#
  prefect-server:
    image: sathyamurthyb4u/prefect-local:2.0.1
    command:
      - prefect
      - orion
      - start
    ports:
      - 4200:4200
    volumes:
      - ${PWD}/prefect:/root/.prefect
      - ${PWD}/flows:/flows
    environment:
      PREFECT_ORION_API_HOST: 0.0.0.0
      PREFECT_ORION_DATABASE_CONNECTION_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      PREFECT_ORION_ANALYTICS_ENABLED: "false"
      PREFECT_LOGGING_SERVER_LEVEL: WARNING
      PREFECT_API_URL: http://${PREFECT_HOST}:4200/api
    networks:
      - prefect
  # --------------------------------------#
  #             Docker Agent              #
  # --------------------------------------#
  prefect-agent:
    image: sathyamurthyb4u/prefect-local:2.0.1
    command:
      - prefect
      - agent
      - start
      - "docker_queue"
    depends_on:
      prefect-server:
        condition: service_started
    environment:
      PREFECT_API_URL: http://${PREFECT_IP}:4200/api
      PREFECT_LOGGING_LEVEL: DEBUG
      DOCKER_HOST: unix://var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - prefect
  # --------------------------------------#
  #         Minio for storage             #
  # --------------------------------------#
  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=one!one!
      - MINIO_ROOT_PASSWORD=one!one!
    volumes:
      - /minio:/data
    command: server /data --console-address :9001
    ports:
      - published: 9000
        target: 9000
      - published: 9001
        target: 9001
    networks:
      - prefect
